### ISSUE TITLE
Multi-file scripts workflow?

### ISSUE THREAD

**Issue by eyalw** [BenGaumond/after-effects#12]
Hey,
How do you recommend working with multiple jsx script files?
I'd love to import/require stuff, but of course it is not possible because of the limitations that exists with the environment. What workaround could maybe do the work?

**Comment by BenGaumond** [comment]
The ReadMe goes into detail about using includes and global declarations within
After Effects. 

I use this package in a couple of server programs in my company, and what I do 
is I run my includes and all of my global declarations when after effects start
up, and then construct my commands clean. Something like so:

`ae.execute(()=> {
  $.global.foo = () => alert('bar')
})
.then(() => {
  console.log('After Effects includes ran.')
})
ae.options.includes = [] //none of my future commands will be created with a bunch
of bundled code that already exists in the AE namespace, anyway`

I think of the After Effects environment the same way I think about the browser;
I try not to worry about the global namespace, because it's already extremely 
polluted with a whole bunch of Adobe functions anyway.

Instead, I keep things organized on the node side and give each of my commands
their own module:

`
/* /src/commands/clear-all-items.js */
import { Command } from 'after-effects'

const clearAllItems = new Command(() => {
  while (app.project.numItems > 0)
    app.project.items(0).remove()
})

export default function () {
  return clearAllItems.execute()
}

export function sync() {
  return clearAllItems.executeSync()
}

`

Then I import the commands as I need them, elsewhere:

`import clearAllItems from './commands/clear-all-items'
import doSomethingElse from './commands/do-something-else'

clearAllItems()
.then(doSomethingElse)`

As for actually having requires and imports INSIDE of After Effects, I had at one
point written a framework that could do this, so I know it's possible. It was 
really only useful to me as a proof of concept, as it depended on global eval
and number of other restrictions. The file system access within After Effects,
for example, is syncronous and very slow.

Hope this helps! Don't hesitate with other questions/suggestions.

**Comment by eyalw** [comment]
thanks :)
