### ISSUE TITLE
get() takes ~1.5s per call

### ISSUE THREAD

**Issue by eyalw** [BenGaumond/after-effects#15]
calling get() takes about 1.5 seconds. calling it 4 times takes ~6s, Is it just for me? 
My project is super super small, just animating 2 text layers and 1 image.

**Comment by eyalw** [comment]
Update: adding a type filter reduced the time dramatically. What is taking so long though for such a small project? is it the Properties that are iterated?

```
const types = [CompItem, TextLayer, AVLayer];
  const target = get(targetName, types).selection(0);
```

**Comment by BenGaumond** [comment]
Yeah, you nailed it. Layers have a great deal of properties. They exist on layers even if they wouldn't be visible to the UI. Placeholders for Time Remap, Layer Styles, effects and so on.

Usually when I get something, i'm doing it like so:

    get.comps('Name').each(comp => /*do whatever with comp */ )

The only problem I see with your query is that you're mixing Comp and Layer types, and reducing the selection to first found item. I actually don't think that should be a problem, because it will add items to the selection before layers, but the layer types there would be redundant.

    const target = get.comps(targetName).selection(0); 

Would also do the a trick and be a bit quicker.

I'm thinking I might split 'get' into it's own repo for the es6 refactor, and document it's API a little better.

**Comment by eyalw** [comment]
Cool, thanks! 👍
