### ISSUE TITLE
Keeping after-effects open after command completed

### ISSUE THREAD

**Issue by JamesWatton** [BenGaumond/after-effects#18]
Hi, I've been using this package for a short while with great success. One thing I've stumbled upon is that if After Effects is not already open, it looks like running a command will launch after effects which is great. However, it looks to be closing after effects after the command has returned/completed.

Is there a way to make after effects remain open?

**Comment by BenGaumond** [comment]
This is definitely not intended behaviour, and I've never seen it do that before. 

This package shouldn't close after effects unless you were to explicitly send an app.quit command:
`ae(() => app.quit())`

Can you tell me more? Windows or Mac? What version of After Effects are you using? Can you

**Comment by JamesWatton** [comment]
Interesting, I thought it was the normal behavior. I'm running the latest version of CC 2017 on Windows 10 Enterprise and also on Windows Server 2012 R2. I have only tried it on windows platforms.

This is the code that reproduces it:

`var project = ae(() => { return app.project; });
console.log(project);
while (true)
{

}

I get after effects loading up and closing almost immediately, and then something printing to the node console.

I've attached the log file from after effects from a single run of the above code. It looks to initialize everything, and then "Ticks = 11031      <41636> <ALOG> <5> BEE Command Close Project" after which it starts cleaning up and closing down.

[After Effects Log.txt](https://github.com/BenGaumond/after-effects/files/713492/After.Effects.Log.txt)

If there's anything else you need that I can help with, let me know. It's not a big issue (for me at least) as After Effects can be launched from a startup script, but it is preferable if the package can handle that as well, especially if it is it's intended behavior to stay open.

Thanks again

**Comment by BenGaumond** [comment]
Definitely this behaviour has something to do with your After Effects installation, and isn't related to this package. Try reinstalling after effects.

A couple other notes:

Returning app.project will just result in an empty object, because the project object inside after effects is not something that can be serialized as JSON. You can't call functions on the project object inside the node environment, just like you couldn't send the fs module to after effects and call fs functions from it's environment. Check the ReadMe for further details.

I'm assuming that infinite while loop is just pseudocode, and there are more statements in there? Otherwise, while this wouldn't change the behaviour of this package, it would definitely make node hang forever.

Good luck!

**Comment by JamesWatton** [comment]
Hi, didn't want to start a new issue for this, but have finally solved the problem I was having after it occurred on my co-workers machines too.

The issue is related to this proeprty being true by default: http://aescript.jecool.net/2716/exitafterlaunchandeval/
It is a windows-only behaviour, and setting this property to false in a script will solve this issue. I would submit a pull request but we have solved it in the mean-time by fixing it within our scripts rather than modify this node module.

Cheers!
